package main

import (
	"net/http"
	"crypto/tls"
	"io"
	"fmt"
)

func main() {
	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go

	// curl -v -u 'Administrator:Y7ovG5jY' -k https://my-rec-1.redis-1.svc.cluster.local:9443/coordination/v1/info

	// TODO: This is insecure; use only in dev environments.
	tr := &http.Transport{
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
	}
	client := &http.Client{Transport: tr}

	req, err := http.NewRequest("GET", "https://my-rec-1.redis-1.svc.cluster.local:9443/coordination/v1/info", nil)
	if err != nil {
		panic(err)
	}
	req.SetBasicAuth("Administrator", "Y7ovG5jY")

	resp, err := client.Do(req)
	if err != nil {
		panic(err)
	}
	defer resp.Body.Close()

	bodyBytes, err := io.ReadAll(resp.Body)
    if err != nil {
        panic(err)
    }
    bodyString := string(bodyBytes)
    fmt.Println(bodyString)
}