apiVersion: v1
kind: ConfigMap
metadata:
  name: jmx-exporter-config
data:
  config.yaml: |
    hostPort: localhost:1099
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    blacklistObjectNames:
      - "org.apache.activemq:clientId=*,*"

    rules:

    - pattern: org.apache.activemq<type=Broker, brokerName=(\S*), destinationType=(\S*), destinationName=(\S*)><>(\w+)
      name: activemq_$2_$4
      attrNameSnakeCase: true
      labels:
        destination: $3

    - pattern: org.apache.activemq<type=Broker, brokerName=(\S*)><>CurrentConnectionsCount
      name: activemq_connections
      type: GAUGE

    - pattern: org.apache.activemq<type=Broker, brokerName=(\S*)><>Total(.*)Count
      name: activemq_$2_total
      type: COUNTER

    - pattern: org.apache.activemq<type=Broker, brokerName=(\S*)><>(.*)PercentUsage
      name: activemq_$2_usage_ratio
      type: GAUGE
      valueFactor: 0.01

    - pattern: 'java.lang<name=([^>]+), type=GarbageCollector><LastGcInfo>duration: (\d+)'
      name: jvm_gc_duration_seconds
      value: $2
      labels:
        name: $1
      type: GAUGE
      # Convert microseconds to seconds
      valueFactor: 0.001

    - pattern: 'java.lang<name=([^>]+), type=GarbageCollector><>CollectionCount: (\d+)'
      name: jvm_gc_collection_count
      value: $2
      labels:
        name: $1
      type: GAUGE
