apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildfly
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: wildfly
  template:
    metadata:
      labels:
        app.kubernetes.io/app: wildfly
    spec:
      containers:
      - name: wildfly
        image: {{ .Values.image }}
        ports:
        - containerPort: 9990
          name: jmx
