apiVersion: v1
kind: ConfigMap
metadata:
  name: config-script
data:
  config.yaml: |
    hostPort: localhost:9001
    lowercaseOutputLabelNames: true
    lowercaseOutputName: true
    rules:
      - pattern: "com.facebook.presto.execution<name=TaskManager><>(.+): (.*)"
        name: "presto_TaskManager_$1"
        value: $2
        type: GAUGE
        attrNameSnakeCase: false
      - pattern: "com.facebook.presto.execution.executor<name=TaskExecutor><>(.+): (.*)"
        name: "presto_TaskExecutor_$1"
        value: $2
        type: GAUGE
      - pattern: "com.facebook.presto.failureDetector<name=HeartbeatFailureDetector><>ActiveCount: (.*)"
        name: "presto_HeartbeatDetector_ActiveCount"
        value: $1
        type: GAUGE
        attrNameSnakeCase: false
      - pattern: "com.facebook.presto.metadata<name=DiscoveryNodeManager><>(.+): (.*)"
        name: "presto_metadata_DiscoveryNodeManager_$1"
        value: $2
        type: GAUGE
        attrNameSnakeCase: false
      - pattern: "com.facebook.presto.execution<name=QueryManager><>(.+): (.*)"
        name: "presto_QueryManager_$1"
        value: $2
        type: GAUGE
      - pattern: "com.facebook.presto.execution<name=QueryExecution><>(.+): (.*)"
        name: "presto_QueryExecution_$1"
        value: $2
        attrNameSnakeCase: false
      - pattern: "com.facebook.presto.memory<name=ClusterMemoryManager><>(.+): (.*)"
        name: "presto_ClusterMemoryManager_$1"
        value: $2
        type: GAUGE
        attrNameSnakeCase: false
      - pattern: "com.facebook.presto.memory<type=ClusterMemoryPool, name=(.*)><>(.+): (.*)"
        name: "presto_ClusterMemoryPool_$1_$2"
        type: GAUGE
      - pattern: "com.facebook.presto.memory<type=MemoryPool, name=(.*)><>(.+): (.*)"
        name: "presto_MemoryPool_$1_$2"
        type: GAUGE
      - pattern: 'java.lang<name=([^>]+), type=GarbageCollector><LastGcInfo>duration: (\d+)'
        name: jvm_gc_duration
        value: $2
        labels:
          name: $1
        type: GAUGE
      - pattern: 'java.lang<name=([^>]+), type=GarbageCollector><>CollectionCount: (\d+)'
        name: jvm_gc_collection_count
        value: $2
        labels:
          name: $1
        type: GAUGE
