apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracledbxe
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: oracledbxe
  template:
    metadata:
      labels:
        app.kubernetes.io/app: oracledbxe
    spec:
      containers:
      - name: oracledbxe
        image: {{ .Values.image }}
        resources:
          limits:
            memory: "3G"
        env:
        - name: ORACLE_PASSWORD
          value: "Evergreen8080"
        - name: APP_USER
          value: "oracleUser"
        - name: APP_USER_PASSWORD
          value: "Evergreen8181"
        ports:
        - containerPort: 1521
