version: '3.0'
services:
  mq-exporter:
    image: mq-metric-prometheus:latest
    container_name: mq-metric-prometheus
    restart: unless-stopped
    ports:
      - 9190:9157
    volumes:
      - ~/tmp/mq-metric-samples/bin/mq_prometheus.yaml:/opt/config/mq_prometheus.yaml
    environment:
      - MQSERVER=SYSTEM.ADMIN.SVRCONN/TCP/'<IP>(<PORT>)'
