apiVersion: v1
kind: Service
metadata:
  labels:
    app: aerospike
    aerospike_cluster: as-cluster-0
  name: aerospike
spec:
  clusterIP: None
  ports:
  - port: 3000
    name: aerospike
  - port: 9145
    name: prometheus
  selector:
    app: aerospike
