apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aerospike
  labels:
    app: aerospike
spec:
  serviceName: aerospike
  replicas: 3
  selector:
    matchLabels:
      app: aerospike
  template:
    metadata:
      labels:
        app: aerospike
        aerospike_cluster: as-cluster-0
    spec:
      containers:
      - name: aerospike
        image: {{ .Values.aerospikeImage }}
        args:
          - --config-file=/opt/aerospike/etc/aerospike.conf
        ports:
        - containerPort: 3000
        - containerPort: 3001
        - containerPort: 3002
        resources:
          limits:
            cpu: "500m"
            memory: 1Gi
        volumeMounts:
        - name: aerospike-config-volume
          mountPath: /opt/aerospike/etc/aerospike.conf
          subPath: aerospike.conf
      - name: aerospike-prometheus-exporter
        image: {{ .Values.exporterImage }}
        ports:
        - containerPort: 9145
          name: prometheus
        env:
          - name: AS_HOST
            value: localhost
          - name: AS_PORT
            value: "3000"
      volumes:
        - name: aerospike-config-volume
          configMap:
            name: aerospike-config
            items:
            - key: aerospike.conf
              path: aerospike.conf
