apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: redb-admission-1
  labels:
    app: redis-enterprise
webhooks:
- name: redb.admission.redislabs
  failurePolicy: Fail
  matchPolicy: Exact
  sideEffects: None
  timeoutSeconds: 30
  rules:
  - apiGroups:   ["app.redislabs.com"]
    apiVersions: ["v1alpha1"]
    operations:  ["*"]
    resources:   ["redisenterprisedatabases"]
  clientConfig:
    service:
      namespace: redis-1
      name: admission
      path: /admission
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURjekNDQWx1Z0F3SUJBZ0lRQWRkYVIySWtaY3QrQWhnUGNuL3p0VEFOQmdrcWhraUc5dzBCQVFzRkFEQSsKTVNRd0lnWURWUVFLRXh0U1pXUnBjMHhoWW5NZ1FXUnRhWE56YVc5dUlFTnZiblJ5YjJ3eEZqQVVCZ05WQkFNVApEV0ZrYldsemMybHZiaTEwYkhNd0hoY05Nak13TkRFek1UY3hPVEF5V2hjTk1qZ3dOREV4TVRjeE9UQXlXakErCk1TUXdJZ1lEVlFRS0V4dFNaV1JwYzB4aFluTWdRV1J0YVhOemFXOXVJRU52Ym5SeWIyd3hGakFVQmdOVkJBTVQKRFdGa2JXbHpjMmx2YmkxMGJITXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFESgpFZG5EaHp1RlMrSWI1aVllZ2xIZm9uSUg0azJuTXFDVUhrYlRKMVZMR3lkUVlnS09YTUgrQWdZcldZa2hsZEFmCkV0ZGxDelBQeUozSUV3cmtvWW1Ma3JXaHNxRFFJT3dMeDAvVlVxK2hYa1ZieUFGd0Y2b044U0h4TXR0RUNBSjUKN2dFcFo1azdtSmd0RThjZDNrM3FkQzhOekNEUjluV0lRN0JMaUo2SFgzRHVRd1E4TnZ4dTFadGVvaEVqVGYrUApybWR3MThxanFVTHlDY0NEVXFpTkh6RUtwQWx3Z0RnNFVoOWtqSzlKUWE5REh3ZXFQNm55emdmRkVjamxuSEhUCkpGc3RXdjBsV2xyY0R5UTM5YnVwYitOZVY0ZWMrbWE3SUh2M0JibGJ2V2JTV2FDUFJic1RKNFJ4MkdHZStwSmEKdHZMczB4VUR6bXY4cHQ1eVJLV1ZBZ01CQUFHamJUQnJNR2tHQTFVZEVRUmlNR0NDQ1dGa2JXbHpjMmx2Ym9JagpZV1J0YVhOemFXOXVMbkpsWkdsekxURXVjM1pqTG1Oc2RYTjBaWEl1Ykc5allXeUNGV0ZrYldsemMybHZiaTV5ClpXUnBjeTB4TG5OMlk0SVJZV1J0YVhOemFXOXVMbkpsWkdsekxUR0hCQXA4RHNjd0RRWUpLb1pJaHZjTkFRRUwKQlFBRGdnRUJBTEZuWXNRc092TWZZN0ZFcE9GTFZiVUlwTWY0STcvMGlBZHpPWUVFRndYUXNkVzdFR09MbStETgorNVd0SDc3SmJCNWIvWmNYRTY0WW1qQUFCK3VNVGZsblRDM3RZeEl2eTA5ekR1TUxKNVc2L2JXWWl0M3Bxb0VRCjBHUWZjRmFSdjEvM2tMdlJmNFVPTHhINjJVdUtDbHVRTUhtck1OSUsrbWdtYjY5c1RldkwwamU1eEdRZWw5Y0MKUnAzeGt3cEl1bS9RR3BlTUtMOU9QSlM5d3lweDd3N3hUNWFyQmNWSjNUMGtxOGtsODFlTVdrV2hwekdtcWxtOQpNRFR2WHFvSnBJTmVsV1VwOGQ1Nm5HVVp0a2pqbGNBQlg2dEQ0dVEvREh0R2dUME1JbUp3WTZyU0MrU0FDeFpSCk1oL0RVM1Q3ak1mQjhuOXFBMGNVdnU4TndDT21SUUE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K" # Fill in with BASE64 encoded signed cert
  admissionReviewVersions: ["v1beta1"]
