apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-promtail-config
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://loki.default.svc.cluster.local:3100/loki/api/v1/push
    scrape_configs:
    - job_name: integrations/clickhouse_logs
      static_configs:
      - targets:
          - localhost
        labels:
          instance: ${INSTANCE}:9363
          job: integrations/clickhouse
          __path__: /var/log/clickhouse-server/clickhouse-server.err.log
      pipeline_stages:
      - multiline:
          firstline: '^([\d]{4}).([\d]{1,2}).([\d]{1,2}) (([\d]+):([\d]+):([\d]+).([\d]+))'
      - regex:
          expression: '(?P<timestamp>(([\d]{4}).([\d]{1,2}).([\d]{1,2}) (([\d]+):([\d]+):([\d]+).([\d]+))) (?P<message>(?s:.*))$)'
