apiVersion: v1
kind: Service
metadata:
  name: mq-metric-prometheus-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9157'
  labels:
    app: mq-metric-prometheus
spec:
  ports:
  - name: metrics
    port: 9157
    targetPort: 9157
    protocol: TCP
  selector:
    app: mq-metric-prometheus-app
  type: ClusterIP