apiVersion: v1
kind: Pod
metadata:
  name: mq-metric-prometheus
  labels:
    app: mq-metric-prometheus-app
spec:
  containers:
    - name: mq-metric-prometheus
      image: uk.icr.io/my-icr-namespace/mq-metric-prometheus:1.0
      envFrom:
      - configMapRef:
          name: metrics-configuration
      - secretRef:
          name: metrics-credentials
  restartPolicy: OnFailure
  imagePullSecrets:
    - name: all-icr-io