apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-interactions
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "delete", "patch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-interactions
subjects:
  - kind: User
    name: my-service-account
roleRef:
  kind: Role
  name: pod-interactions
  apiGroup: rbac.authorization.k8s.io
