{{- if (include "discourse.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-discourse" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if not .Values.auth.existingSecret }}
  discourse-password: {{ include "common.secrets.passwords.manage" (dict "secret" (printf "%s-discourse" (include "common.names.fullname" .)) "key" "discourse-password" "providedValues" (list "auth.password") "context" $) }}
  {{- end }}
  {{- if and .Values.smtp.enabled .Values.smtp.password (not .Values.smtp.existingSecret) }}
  smtp-password: {{ .Values.smtp.password | b64enc | quote }}
  {{- end }}
{{- end }}
