apiVersion: v1
kind: ConfigMap
metadata:
  name: prestodb-coordinator
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: prestodb
    app.kubernetes.io/component: coordinator
    app.kubernetes.io/version: {{ .Values.image.tag | default .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  node.properties: |-
    node.location={{ .Values.node.location }}
    node.environment={{ .Values.node.environment }}
    node.data-dir={{ .Values.node.dataDir }}
  jvm.config: |-
    {{- .Values.coordinator.jvm | default .Values.jvm | nindent 4 }}
  config.properties: |-
    coordinator=true
    http-server.http.port={{ .Values.service.port }}
    discovery.uri=http://prestodb-discovery:{{ .Values.service.port }}
    discovery-server.enabled={{ or (eq .Values.mode "single") (eq .Values.mode "cluster") }}
    node-scheduler.include-coordinator={{ eq .Values.mode "single" }}
    resource-manager-enabled={{ eq .Values.mode "ha-cluster" }}
    {{- .Values.config | nindent 4 }}
  log.properties: |-
    {{- .Values.log | nindent 4 }}
