apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apache-cassandra
spec:
  serviceName: apache-cassandra
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/app: apache-cassandra
  template:
    metadata:
      labels:
        app.kubernetes.io/app: apache-cassandra
        cassandra_cluster: operator:cassandra-cluster
    spec:
      containers:
      - name: apache-cassandra
        image: {{ .Values.image }}
        env:
          - name: CASSANDRA_SEEDS
            value: "apache-cassandra-0.apache-cassandra.sample-apps.svc.cluster.local"
          - name: CASSANDRA_DC
            value: "TEST_DC"
          - name: CASSANDRA_CLUSTER_NAME
            value: "test-cluster"
          - name: JVM_OPTS
            value: "-Xms1024M -Xmx2048M -XX:MaxPermSize=1024M -XX:MaxHeapSize=2048M"
          - name: MAX_HEAP_SIZE
            value: 2048M
          - name: HEAP_NEWSIZE
            value: 512M
          - name: CASSANDRA_LISTEN_ADDRESS
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        ports:
        - name: client
          containerPort: 9042
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /ready-probe.sh
          initialDelaySeconds: 60
          timeoutSeconds: 30
          failureThreshold: 5
        resources:
          limits:
            memory: 2.5G
          requests:
            cpu: "500m"
            memory: 2.5G
      - name: jmx-exporter
        image: bitnami/jmx-exporter:0.17.2
        ports:
        - name: exporter
          containerPort: 9000
        command:
          - java
          - -jar
          - jmx_prometheus_httpserver.jar
        args:
          - "9000"
          - config.yaml
        volumeMounts:
        - mountPath: /opt/bitnami/jmx-exporter/config.yaml
          subPath: config.yaml
          name: config-script
      volumes:
      - name: config-script
        configMap:
          name: config-script
          defaultMode: 0644
          items:
          - key: config.yaml
            path: config.yaml
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: apache-cassandra-loadgen
  namespace: sample-apps
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      parallelism: 1
      template:
        spec:
          containers:
          - name: apache-cassandra-loadgen
            image: {{ .Values.image }}
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            # ignore errors as to skip read validations when running on mixed mode
            - /opt/cassandra/tools/bin/cassandra-stress write n=1 -node 'apache-cassandra.sample-apps.svc.cluster.local:9042' -errors ignore &&  /opt/cassandra/tools/bin/cassandra-stress mixed n=100 -node 'apache-cassandra.sample-apps.svc.cluster.local:9042' -errors ignore
          restartPolicy: Never
