apiVersion: v1
kind: Service
metadata:
  name: apache-cassandra
  labels:
    app.kubernetes.io/service: apache-cassandra
    cassandra_cluster: test-cluster
spec:
  selector:
    app.kubernetes.io/app: apache-cassandra
  ports:
    - name: jmx
      protocol: TCP
      port: 7199
      targetPort: 7199
    - name: apache-cassandra
      protocol: TCP
      port: 7000
      targetPort: 7000
    - name: client
      protocol: TCP
      port: 9042
      targetPort: 9042
    - name: exporter
      protocol: TCP
      port: 9000
      targetPort: 9000
