apiVersion: v1
kind: ConfigMap
metadata:
  name: master-start-script
data:
  startup.sh: |
    #!/bin/bash

    # Run mesos master and exporter in the background
    mesos-master --work_dir=/var/lib/mesos --log_dir=/var/log/mesos/ &
    /mesos_exporter-1.1.2.linux-*/mesos_exporter -master http://localhost:5050
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-start-script
data:
  startup.sh: |
    #!/bin/bash

    # Run mesos agent and exporter in the background
    mesos-agent --work_dir=/var/lib/mesos/agent --log_dir=/var/log/mesos --master=localhost:5050 --launcher=posix --systemd_enable_support=false
