apiVersion: v1
kind: Service
metadata:
  name: apache-mesos
spec:
  selector:
    app.kubernetes.io/app: apache-mesos
  ports:
    - name: mesos-master
      protocol: TCP
      port: 5050
      targetPort: 5050
    - name: mesos-agent
      protocol: TCP
      port: 5051
      targetPort: 5051
    - name: mesos-exporter
      protocol: TCP
      port: 9105
      targetPort: 9105
