name: Apache Mesos Build Test

on:
  push:
    branches:
      - main
    paths:
      - "container/apache-mesos"
      - ".github/workflows/apache-mesos.yaml"
  workflow_dispatch:

jobs:
  push-images:
    runs-on: ubuntu-latest-arm-2-cores
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Tag From Environment
        id: get-tag
        run: printf '::set-output name=tag::%s' "$(git rev-parse --short HEAD)"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build test
        uses: docker/build-push-action@v2
        with:
          context: container/apache-mesos
          file: container/apache-mesos/Dockerfile
          platforms: linux/arm64,linux/amd64
          push:  false
          tags:  ghcr.io/observiq/apache-mesos:${{ steps.get-tag.outputs.tag }}
