name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  helm:
    strategy:
      matrix:
        chart:
          - "clickhouse"
          - "discourse"
          - "tensorflow"
          - "wildfly"
          - "mssql"
          - "oracledbxe"
          - "apache-cassandra"
          - "squid"
          - "apache-mesos"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Helm Check
        uses: igabaydulin/helm-check-action@0.1.4
        env:
          CHART_LOCATION: ./charts/${{ matrix.chart }}
          CHART_VALUES: ./charts/${{ matrix.chart }}/values.yaml
