name: Release Container Images

on:
  push:
    branches:
      - main
    paths:
      - "container/**"
      - ".github/workflows/container.yaml"
  pull_request:

jobs:
  push-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - "discourse"
          - "rubyexporter"
          - "tensorflow"
          - "tensorflowload"
          - "wildfly"
          - "cassandra"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # - name: Set GITHUB_SHA_SHORT
      #   run: echo "GITHUB_SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Get Tag From Environment
        id: get-tag
        run: printf '::set-output name=tag::%s' "$(git rev-parse --short HEAD)"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: container/${{ matrix.app }}
          file: container/${{ matrix.app }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false # true
          tags:  ghcr.io/observiq/${{ matrix.app }}:${{ steps.get-tag.outputs.tag }}