name: Build/Release IBM MQ Exporter

on:
  pull_request:
    branches:
      - main

jobs:
  push-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app:
          - "mq-metric-samples"
    steps:
      - name: Initialize Submodules
        uses: snickerbockers/submodules-init@v4

      - name: Get Tag From Environment
        id: get-tag
        run: printf '::set-output name=tag::%s' "$(git rev-parse --short HEAD)"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: submodules/${{ matrix.app }}
          file: submodules/${{ matrix.app }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push:  true
          tags:  ghcr.io/observiq/${{ matrix.app }}:${{ steps.get-tag.outputs.tag }}
