apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen       8080;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

        location /status {
            stub_status on;
            access_log  on;           
            allow all;
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: varnish-secret
data:
  # Use a real secret in production, not a configmap.
  secret: |
    replace-with-real-secret
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: varnish-config
data:
  default.vcl: |
    vcl 4.1;

    probe health {
        .url = "/";
        .timeout = 2s;
        .interval = 5s;
        .window = 5;
        .threshold = 3;
    } 

    backend server_nginx_0 {
        .host = "localhost";
        .port = "8080";
        .probe = health;
    }
---
