apiVersion: v1
kind: ConfigMap
metadata:
  name: varnish-config
data:
  # Use a real secret in production, not a configmap.
  secret: |
    replace-with-real-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: varnish
  namespace: default
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: varnish
  template:
    metadata:
      name: varnish
      labels:
        app: varnish
    spec:
      # Process namespace sharing is required for the varnish and exporter containers
      # to share the Varnish working directory.
      shareProcessNamespace: true
      containers:
      - name: varnish
        env:
          - name: VARNISH_HTTP_PORT
            value: "8080"
        image: {{ .Values.varnishImage }}
        volumeMounts:
          - name: varnish-config
            mountPath: /etc/varnish/secret
            subPath: secret
          - name: shared-data
            mountPath: /var/lib/varnish
      - name: exporter
        command:
          - "/prometheus_varnish_exporter"
        image: {{ .Values.exporterImage }}
        volumeMounts:
          - name: shared-data
            mountPath: /var/lib/varnish
            readOnly: true
        ports:
        - containerPort: 9131
          name: prometheus
      volumes:
        - name: varnish-config
          configMap:
            name: varnish-config
        - name: shared-data
          emptyDir: {}
