apiVersion: apps/v1
kind: Deployment
metadata:
  name: varnish
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: varnish
  template:
    metadata:
      name: varnish
      labels:
        app: varnish
    spec:
      # Process namespace sharing is required for the varnish and exporter containers
      # to share the Varnish working directory.
      shareProcessNamespace: true
      containers:
      - name: nginx
        image: {{ .Values.nginxImage }}
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
      - name: varnish
        image: {{ .Values.varnishImage }}
        volumeMounts:
          - name: varnish-secret
            mountPath: /etc/varnish/secret
            subPath: secret
          - name: shared-data
            mountPath: /var/lib/varnish
          - name: varnish-config
            mountPath: /etc/varnish/default.vcl
            subPath: default.vcl
      - name: exporter
        command:
          - "/prometheus_varnish_exporter"
        image: {{ .Values.exporterImage }}
        volumeMounts:
          - name: shared-data
            mountPath: /var/lib/varnish
            readOnly: true
        ports:
        - containerPort: 9131
          name: prometheus
      volumes:
        - name: varnish-secret
          configMap:
            name: varnish-secret
        - name: varnish-config
          configMap:
            name: varnish-config
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: shared-data
          emptyDir: {}
