apiVersion: v1
kind: Service
metadata:
  name: custom-varnish-cache
  labels:
    helm.sh/chart: varnish-cache-0.1.0
    app.kubernetes.io/name: varnish-cache
    app.kubernetes.io/instance: custom
    app.kubernetes.io/version: "7.4.2"
    app.kubernetes.io/managed-by: Helm      
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: varnish-exporter
      port: 9131
      targetPort: 9131
  selector:
    app.kubernetes.io/name: varnish-cache
    app.kubernetes.io/instance: custom
