apiVersion: v1
kind: Service
metadata:
  name: varnish-service
  labels:
    app: varnish
spec:
  ports:
  - port: 9131
    name: varnish-exporter
  - port: 8080
    name: nginx
  selector:
    app: varnish
