apiVersion: v1
kind: Service
metadata:
  name: varnish-service
  labels:
    app: varnish
spec:
  ports:
  - port: 9131
    name: varnish-exporter
  - port: 80
    name: varnish-reverse-proxy
  selector:
    app: varnish
