apiVersion: v2
name: presto
description: Customized version of the official Helm chart for Presto
type: application
version: 1.0.1
appVersion: "0.283"
home: https://prestodb.io
icon: https://prestodb.io/docs/current/_static/logo.png
keywords:
  - presto
  - prestodb
sources:
  - https://github.com/prestodb/presto
  - https://github.com/prestodb/presto-helm-charts
